import { FC, ReactNode } from 'react';
import '@/styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import Provider from '@/components/providers/auth-provider';
import { SocketProvider } from '@/components/providers/socket-provider';
import Topbar from '@/components/shared/Authenticated/Topbar';
import Leftsidebar from '@/components/shared/Authenticated/Leftsidebar';
import Rightsidebar from '@/components/shared/Authenticated/Rightsidebar';
import Bottombar from '@/components/shared/Authenticated/Bottombar';
import { QueryProvider } from '@/components/providers/query-provider';
import { ModalProvider } from '@/components/providers/modal-provider';
import Notifikasi from '@/components/shared/Authenticated/Notifikasi';
import { ThemeProvider } from '@/components/providers/theme-provider';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface AuthenticatedLayoutProps {
    children: ReactNode;
}

const AuthenticatedLayout: FC<AuthenticatedLayoutProps> = async ({ children }) => {

    const session = await getServerSession(authOptions)

    // jika tidak ada session arahkan ke page /
    const apiUrl = '/api/notif'


    return (
        <Provider session={session}  >
            <html lang='en'>
                <body className={inter.className}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem={false}
                        disableTransitionOnChange
                    // storageKey="discord-theme"
                    >
                        <Topbar />
                        <main className='flex flex-row'>
                            <Leftsidebar />
                            <section className='main-container'>
                                <div className='w-full '>
                                    <SocketProvider>
                                        <QueryProvider>
                                            <Notifikasi
                                                apiUrl={apiUrl}
                                            />
                                            <ModalProvider />
                                            {children}
                                        </QueryProvider>
                                    </SocketProvider>
                                </div>
                            </section>
                            {/* <Rightsidebar /> */}
                        </main>
                        <Bottombar />
                    </ThemeProvider>
                </body>
            </html>
        </Provider>
    );
};

export default AuthenticatedLayout;