name: Build and Push

on:
  workflow_run:
    workflows: ["Node.js CI"]
    types: 
      - completed

permissions:
      contents: read
      packages: write

env:
  VER_TAG: v0.1.0
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            yoganovaindra/dombacerdas-web:${{ env.VER_TAG }}
            yoganovaindra/dombacerdas-web:latest
            ghcr.io/yoganovvaindra/dombacerdas-web:${{ env.VER_TAG }}            
            ghcr.io/yoganovvaindra/dombacerdas-web:latest